
language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

install:
    - pip install scrutinizer-ocular coverage webtest httmock requests ppp_datamodel ppp_libmodule nltk ply
    - sudo add-apt-repository ppa:webupd8team/java -y
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer

before_script:
  - ./get_dependencies.sh
  - ./setup.py install

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
